name: 'TfxInstaller'
description: 'Install tfx-cli inside the tool cache.'
author: 'Kevin Lecouvey'
inputs:
  version: 
    required: true
    description: 'Specify which tfx-cli version you want to use. Ex.: v0.8x, >=v0.5.x'
    default: 'v0.8.x'
  checkLatest:
    required: false
    description: 'Automatically download the latest version of tfx-cli'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
